---
title: "mammalia_ML"
output: html_document
date: '2023-08-11'
---

```{r setup, include=FALSE}
library(readxl)
mammalia <- read_excel("~/Desktop/Internship/ML_excel_files/mammalia_ML.xlsx")
```

```{r, mammalia: Browsing the data }
head(mammalia) #shows top few handful of rows with column names
mammalia$threat <- as.factor(mammalia$threat) #response variable needs to be a factor
table(mammalia$threat)
mammalia$population_stability_trends <- as.factor(mammalia$population_stability_trends)
mammalia$movement_pattern <- as.factor(mammalia$movement_pattern)
mammalia$system <- as.factor(mammalia$system)

data.imputed <- rfImpute(threat~., data = mammalia, iter=3) #everything needs to be a factor 

```

##Partitoining the data: Training and Test
```{r, data partioning}
#Need to split test and training set
set.seed(11) #set seed so model outcome is repeatable
ind <- sample(2, nrow(data.imputed), replace = TRUE, prob = c(0.7, 0.3)) #training/test %70/%30
train <- data.imputed[ind==1,]
test <- data.imputed[ind==2,]

```

##Building the random forest#
OOB estimate error rate: 100-error rate = % of OOB samples that were correctly classified by the random forest 
```{r, random forest}

set.seed(8)
rf_mammalia <- randomForest(threat~., data=train, ntree=300, proximity= TRUE, importance = TRUE)
rf_mammalia
```

#Confusion Matrix 
```{r}
#confusion matrix for accuracy of training and test dataset 
p1 <- predict(rf_mammalia, train)
confusionMatrix(p1, train$threat)
p2 <- predict(rf_mammalia, test)
confusionMatrix(p2, test$threat) 

#Sensitivity is the percentage of true records that you predicted correctly. Specificity, on the other hand, is to measure what portion of the actual false records you predicted correctly.

```

##Error Rate of Random Forest#
```{r}
#this is based on a matrix within "train" (randomForest model above) called err.rate
oob.error.data <- data.frame(
  Trees=rep(1:nrow(rf_mammalia$err.rate), times=3),
  Type=rep(c("OOB", "Threatened", "Non Threatened"), each=nrow(rf_mammalia$err.rate)),
  Error=c(rf_mammalia$err.rate[,"OOB"],
    rf_mammalia$err.rate[,"Threatened"],
    rf_mammalia$err.rate[,"Non Threatened"]))


#call to ggplot train model
ggplot(data=oob.error.data, aes(x=Trees, y=Error))+
  geom_line(aes(color=Type))+
  xlab("Number of Trees (ntrees)")+
  ylab("Error rate")+
  ggtitle("Error rate of random forest model for class mammalia")+
  theme_bw()

#for this model, error rate stabilizes after 100 trees- this is probably due to low data points
```

```{r, importance plot}
varImpPlot(rf_mammalia)
#generates importance plot (for this model fst is the most important attribute when predicting threat)

##Mean decrease in accuracy, population stability is the strongest predictor 

#variable measures
vi_rf <- rf_mammalia$variable.importance #mean decrease in accuracy

imp.plot <- vip(rf_mammalia)
imp.plot + xlab("Model features") + ylab("Mean Decrease Accuracy")+ 
  ggtitle("Class Mammalia Model Feature Importance")+
  theme_light()

vip(rf_mammalia, num_features = 7, geom = "point", horizontal = FALSE,
aesthetics = list(color = "red", shape = 17, size = 7)) +
xlab("Model features")+ ggtitle("Mean Decrease Accuracy")+
theme_light()

print(varImp(rf_mammalia))

```