---
title: "Preliminary Stats: SNP data
output: html_document
date: '2023-03-27'
---

```{r setup, include=FALSE}

library(readxl)
library(ggpubr)
library(car)
library(dplyr)

setwd("~/Desktop/Thesis")

SNP_mammals <- read_excel("~/Desktop/Thesis/mammals_SNP.xlsx")
SNP_fish <- read_excel("~/Desktop/Thesis/fish_SNP.xlsx")
SNP_birds <- read_excel("~/Desktop/Thesis/birds_SNP.xlsx")

constatus <- factor(c("Least Concern", "Near Threatened", "Vulnerable", "Endangered", "Critically Endangered"), ordered = TRUE) #order by IUCN ranking for graphs
```

##Mammals##
```{r}

#check sample size for mammals data set
SNP_mammals %>% 
  count(observed) #19 measures of ob het in this dataset
SNP_mammals %>% #10
  count(fst)
SNP_mammals %>% #4
  count(allelic.richness)


## Shapiro Wilks Test of Normality
#Check Data for Normality Using Shapiro Wilks Test p value < 0.05 indicates that the data is not normal
shapiro.test(SNP_mammals$observed) #did not pass normality
shapiro.test(log(SNP_mammals$observed)) #did not pass
shapiro.test(SNP_mammals$fst) #p=0.2804 passed normality
shapiro.test(SNP_mammals$allelic.richness) #p=0.1159 passed normality- theres only 4 data points though..

## Levenes test of Homogeneity of variance 
leveneTest(observed~iucn, data = SNP_mammals) #passed, p=0.1256
leveneTest(fst~iucn, data = SNP_mammals) #passed, p=0.115

```

## Birds ##
```{r}
## Shapiro Wilks Test of Normality
#Check Data for Normality Using Shapiro Wilks Test p value < 0.05 indicates that the data is not normal
shapiro.test(SNP_birds$observed) #passed, 0.06164
shapiro.test(SNP_birds$fst) # did not pass 0.006596
shapiro.test(log(SNP_birds$fst)) #passed after log transformation, p= 0.03393


## Levenes test of Homogeneity of variance 
#there is only one endangered study so we can't even compare anything.. 
```


## Fish ##
```{r}
#check sample size for fish data set
SNP_fish %>% 
  count(observed) #28 measures of ob het in this dataset
SNP_fish %>% #31
  count(fst)


## Shapiro Wilks Test of Normality
#Check Data for Normality Using Shapiro Wilks Test p value < 0.05 indicates that the data is not normal
shapiro.test(SNP_fish$observed) #passed  p=0.0348
shapiro.test(SNP_fish$fst) #failed p=4.7e-09
shapiro.test(log(SNP_fish$fst)) #NA?

## Levenes test of Homogeneity of variance 
leveneTest(observed~iucn, data = SNP_fish) #passed, p=0.4746
leveneTest(fst~iucn, data = SNP_fish) #failed p=0.00025

```
