---
title: "Violin plots: visualizing data distribution"
date: 8/2023
output: html_notebook
---


```{r, setup, libs}
library(ggplot2)
library(dplyr)
library(ggstance)
library(Hmisc)
library(wesanderson)
library(readxl) #read in excel files
library(ggpubr)
library(car)

#read in data
#data from these files were collated from DataDryad
mammals <- read_excel("~/Desktop/ML_aoki23/statistical_analysis/mammals_msat.xlsx")
birds <- read_excel("~/Desktop/ML_aoki23/statistical_analysis/birds_msat.xlsx")
fish <- read_excel("~/Desktop/ML_aoki23/statistical_analysis/fish_msat.xlsx")
reptiles <- read_excel("~/Desktop/ML_aoki23/statistical_analysis/reptiles_msat.xlsx")
amphibians <- read_excel("~/Desktop/ML_aoki23/statistical_analysis/amphibians_msat.xlsx")

```

##### Class Aves ######
```{r, violin plots}

birds$iucn <- factor(birds$iucn, #arranges axis by RedList rank
                       c("Least Concern", "Near Threatened", "Vulnerable", "Endangered", "Critically Endangered"))

ob <- ggplot(data = birds, mapping = aes(x = birds$iucn, y = observed))+ 
  geom_violin(aes(fill=iucn),show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Observed Heterozygosity") +
  theme_bw()

arb <- ggplot(data = birds, mapping = aes(x = birds$iucn, y = allelic.richness))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Allelic Richness") +
  theme_bw()

mab <- ggplot(data = birds, mapping = aes(x = birds$iucn, y = mean.alleles))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Mean # of Alleles") +
  theme_bw()

fstb <- ggplot(data = birds, mapping = aes(x = birds$iucn, y = fst))+
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Fst") +
  theme_bw()

#combine four figures
avess <- ggarrange(ob, fstb, arb, mab,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2) 

annotate_figure(avess, top = text_grob("Studies of species in the class Aves", 
               color = "black", face = "bold", size = 14))

```

###### Class Mammalia ######
```{r}

mammals$iucn <- factor(mammals$iucn,
                       c("Least Concern", "Near Threatened", "Vulnerable", "Endangered", "Critically Endangered"))
om <- ggplot(data = mammals, mapping = aes(x = mammals$iucn, y = observed))+ 
  geom_violin(aes(fill=iucn),show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Observed Heterozygosity") +
  theme_bw()

arm <- ggplot(data = mammals, mapping = aes(x = mammals$iucn, y = allelic.richness))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Allelic Richness") +
  theme_bw()

mam <- ggplot(data = mammals, mapping = aes(x = mammals$iucn, y = mean.alleles))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Mean # of Alleles") +
  theme_bw()

fstm <- ggplot(data = mammals, mapping = aes(x = mammals$iucn, y = fst))+
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Fst") +
  theme_bw()

mammalss <- ggarrange(om, fstm, arm, mam,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2) 

annotate_figure(mammalss, top = text_grob("Studies of species in the class Mammalia", 
               color = "black", face = "bold", size = 14))
```

##### Class Actinopterygii ######
```{r}

fish$iucn <- factor(fish$iucn,
                       c("Least Concern", "Near Threatened", "Vulnerable", "Endangered", "Critically Endangered"))
of <- ggplot(data = fish, mapping = aes(x = fish$iucn, y = observed))+ 
  geom_violin(aes(fill=iucn),show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Observed Heterozygosity") +
  theme_bw()

arf <- ggplot(data = fish, mapping = aes(x = fish$iucn, y = allelic.richness))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Allelic Richness") +
  theme_bw()

maf <- ggplot(data = fish, mapping = aes(x = fish$iucn, y = mean.alleles))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Mean # of Alleles") +
  theme_bw()

fstf <- ggplot(data = fish, mapping = aes(x = fish$iucn, y = fst))+
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Fst") +
  theme_bw()

fishs <- ggarrange(of, fstf, arf, maf,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2) 

annotate_figure(fishs, top = text_grob("Studies of species in the class Actinopterygii", 
               color = "black", face = "bold", size = 14))
```

##### Class Reptilia #######
```{r}

reptiles$iucn <- factor(reptiles$iucn,
                       c("Least Concern", "Near Threatened", "Vulnerable", "Endangered", "Critically Endangered"))
orep <- ggplot(data = reptiles, mapping = aes(x = reptiles$iucn, y = observed))+ 
  geom_violin(aes(fill=iucn),show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Observed Heterozygosity") +
  theme_bw()

arrep <- ggplot(data = reptiles, mapping = aes(x = reptiles$iucn, y = allelic.richness))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Allelic Richness") +
  theme_bw()

marep <- ggplot(data = reptiles, mapping = aes(x = reptiles$iucn, y = mean.alleles))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Mean # of Alleles") +
  theme_bw()

fstrep <- ggplot(data = reptiles, mapping = aes(x = reptiles$iucn, y = fst))+
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Fst") +
  theme_bw()

reptiles <- ggarrange(orep, fstrep, arrep, marep,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2) 

annotate_figure(reptiles, top = text_grob("Studies of species in the class Reptilia", 
               color = "black", face = "bold", size = 14))
```


##### Class Amphibia #####
```{r}

amphibians$iucn <- factor(amphibians$iucn,
                       c("Least Concern", "Near Threatened", "Vulnerable", "Endangered", "Critically Endangered"))
oamp <- ggplot(data = amphibians, mapping = aes(x = amphibians$iucn, y = observed))+ 
  geom_violin(aes(fill=iucn),show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Observed Heterozygosity") +
  theme_bw()

aramp <- ggplot(data = amphibians, mapping = aes(x = amphibians$iucn, y = allelic.richness))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Allelic Richness") +
  theme_bw()

maamp <- ggplot(data = amphibians, mapping = aes(x = amphibians$iucn, y = mean.alleles))+ 
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Mean # of Alleles") +
  theme_bw()

fstamp <- ggplot(data = amphibians, mapping = aes(x = amphibians$iucn, y = fst))+
  geom_violin(aes(fill=iucn), show.legend = FALSE)+
  geom_boxplot(width=0.1)+
  xlab("IUCN RedList Ranking") + ylab("Fst") +
  theme_bw()

amps <- ggarrange(oamp, fstamp, aramp, maamp,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2) 

annotate_figure(amps, top = text_grob("Studies of species in the class Amphibia", 
               color = "black", face = "bold", size = 14))
```

